### ISSUE TITLE
Feature request, DeclaD

### ISSUE THREAD

**Issue by StevenCTimm** [ivmfnal/protodune#1]
Currently the DeclaD can declare metadata to SAM.  We would like it to also declare the first location into SAM.  This is required because we will be in hybrid mode for a while and both SAM and metacat/rucio will be functioning.

**Comment by ivmfnal** [comment]
It would be useful to have an example of such a declaration. In particular, how the physical path of the file being declared is translated to the location to be declared to SAM

**Comment by StevenCTimm** [comment]
From the samweb command line the command would be

samweb add-file-location <filename> <location>

Filename would be the normal SAM file name and the location would be in sam format of
datadisk:/path. 

dunepro@dunesl7gpvm01 ~]$ samweb locate-file np04_raw_run005716_0001_dl1.root
rucio:protodune-sp
castor:/neutplatform/protodune/rawdata/np04/detector/None/raw/07/39/33/19
enstore:/pnfs/dune/tape_backed/dunepro/protodune/np04/beam/detector/None/raw/07/39/33/19(1549@vr0179m8)

-----

For the cases we are dealing with (cern-eos, enstore, castor, rucio) the locations look like this

[dunepro@dunesl7gpvm01 ~]$ samweb locate-file 1914_2_d_cb.test
rucio:vd-coldbox-top
cern-eos:/eos/experiment/neutplatform/protodune/rawdata/np02/rawdata_cb/1914
enstore:/pnfs/dune/tape_backed/dunepro/vd-coldbox-top/raw/2022/detector/study/None/00/00/19/14(4530@fb0521l9)
castor:/neutplatform/

The corresponding routine in the samweb Python API is addFileLocation(samweb,filenameorid,location)
and can be found in python/samweb_client/files.py

**Comment by ivmfnal** [comment]
Currently the mover has absolute path to the top of the xrootd namespace in the drop RSE and relative path of the file.
How much flexibility do we want to have translating the relative path to the path in terms of SAM location declaration ?

Would the sam disk name be constant for the DecalD instance ?

**Comment by StevenCTimm** [comment]
There is a one to one mapping between RSE and sam disk name.  We will have to do this, in general, 
at two different sites, namely at CERN (DUNE_CERN_EOS) and at FNAL_DCACHE.  
Some flexibility/configurability is in order I think.  Perhaps an optional SAM_PREFIX would be the right way to go in which we can configure samdisk:/the/top/path 
to which the relative path of the file would be appended.

The other piece of the puzzle I realize that we have not yet tried, is in general what happens if the DeclaD is running on 
top of a rucio non-deterministic site such as FNAL_DCACHE.. will it do the right thing even declaring the file to Rucio much less to SAM.  We'll be testing that shortly in the declad that Doug is setting up at Fermilab.

Steve

**Comment by ivmfnal** [comment]
Because the drop RSE is a constant for a DeclaD instance, I suppose the SAM disk name will be a constant too. Right ?

As for the non-deterministic RSE issue, I think, if needed, this can be handles through another issue

**Comment by ivmfnal** [comment]
I am adding 2 new config options:

```
sam_location_template: "samdisk:/top/path/$dst_rel_path"       # relative
sam_location_template: "samdisk:$dst_data_path"                     # absolute

lfn2pfn: rucio        # default, the standard Rucio algorithm for deterministic RSEs
lfn2pfn: dune        # DUNE algorithm to produce relative path based on the file metadata
```
How is that ?

**Comment by StevenCTimm** [comment]
The sam options are good.
with respect to the 2 lfn2pfn options I would prefer to keep them the same as the naming convention that we use 
in rucio, namely hash, and dune (rather than rucio and dune)

**Comment by ivmfnal** [comment]
Done and passed some basic tests.
Some additional bug fixing may be needed as we go into production.
To use it, make sure to upgrade pythreader (pip3 install [--user] --upgrade pythreader). Make sure the version is >= 2.11.0

New config parameter added:

```
sam_location_template: eos:/top/path/$dst_rel_path
```
