### ISSUE TITLE
Change DeclaD to convert all upper case SAM categories to lower case

### ISSUE THREAD

**Issue by StevenCTimm** [ivmfnal/protodune#2]
It was decided (and implemented in MetaCat DB) that all fields such as DUNE.campaign should have their field names
(but not necessarily their content) converted to lowercase on SAM to Metacat conversion.  This needs to be done in the DeclaD as well.

**Comment by ivmfnal** [comment]
Done.
To use this feature, at the top level of the config file, add `lowercase_meta_names: yes`, e.g.:

```
max_movers: 10                          # default 10
queue_capacity: 100                     # stop scanning for input files if the queue is backlogged. default - no limit
retry_cooldown: 3600                    # file retry interval
keep_interval: 86400                    # interval to keep file processing log in memory

lowercase_meta_names: yes

metacat_dataset:    dune:all                # namespace:name
```

Note that this is done only for MataCat metadata, not metadata to be declared to SAM. Please confirm that we do not need to do the same on SAM side too

**Comment by StevenCTimm** [comment]
We do not need to lowercase SAM, nor should we do so.

What's the declad release version that has this option available?

**Comment by ivmfnal** [comment]
the version is 1.8.0
